### PR TITLE
tiny bugfix

### PR DESCRIPTION
**Pull request by FocuzJS**
fix bug that caused UObjects to get detected as empty :)
im not sure that you intended that to be a return false there or not, please get back to me about this

### CODE REVIEW

**Review by corrm — COMMENTED** [review]
thank you for helping fetch and solve bugs,
you are right, but `ReadData` will return `false` only if it's can't read data from `target process`.
so it's critical problem, so we need to stop the tool then.

**Comment by corrm** [comment]
i closed the pull by mistake.

**Comment by FocuzJS** [comment]
> 
> 
> thank you for helping fetch and solve bugs,
> you are right, but `ReadData` will return `false` only if it's can't read data from `target process`.
> so it's critical problem, so we need to stop the tool then.

I could not dump the game splitgate without changing that return false to a continue, just because the first read fails, donesn't mean that the entire gobjects address is bad (and thats what your tool was assuming). I still think this needs fixed, or  you need to see the issue for yourself. Download Splitgate and test.

**Comment by corrm** [comment]
then pls sync and compile the tool from the src and check again i changed the way that get GObjects.
if it's the same i will download this game and test it.

**Comment by FocuzJS** [comment]
i've tested and it's the same as before. I advise you include my simple fix from this PR in your next release and i'll close this, thanks!

**Comment by corrm** [comment]
Sorry for the lateness try version [3.0.0](https://github.com/CorrM/Unreal-Finder-Tool/releases/latest)
and let me know what's happen.

**Pull request closed without merging**
